// Mock data for projects
export const projectsData = [
  {
    id: 1,
    name: "E-commerce Platform",
    company: "TechStartup Inc",
    status: "active",
    startedDate: "2024-01-15",
    pipelineState: "in progress",
    initialPricing: 15000,
    finalPrice: 18500,
    projectType: "Software Factory",
    mmr: 2500,
    paymentStatus: "paid",
    description:
      "Full-featured e-commerce platform with inventory management, payment processing, and customer analytics dashboard.",
    docsLink: "https://docs.example.com/ecommerce-platform",
    milestones: [
      {
        date: "2024-01-15",
        type: "kickoff",
        name: "Project Kickoff",
        description: "Project initialization and team onboarding",
        deliverable: "Project charter and team setup",
      },
      {
        date: "2024-02-15",
        type: "design",
        name: "Design Phase Complete",
        description: "UI/UX design and architecture finalized",
        deliverable: "Design system and wireframes",
      },
      {
        date: "2024-03-15",
        type: "development",
        name: "Core Development",
        description: "Main feature development",
        deliverable: "Core features implemented",
      },
      {
        date: "2024-04-15",
        type: "testing",
        name: "QA Testing",
        description: "Quality assurance and bug fixes",
        deliverable: "Test reports and fixes",
      },
      {
        date: "2024-05-15",
        type: "launch",
        name: "Production Launch",
        description: "Platform goes live",
        deliverable: "Live platform",
      },
    ],
  },
  {
    id: 2,
    name: "Mobile App Development",
    company: "FutureWorks Ltd",
    status: "active",
    startedDate: "2024-02-20",
    pipelineState: "in progress",
    initialPricing: 25000,
    finalPrice: 28000,
    projectType: "Accelleration",
    mmr: 4200,
    paymentStatus: "partial",
    description: "Native iOS and Android mobile application with real-time synchronization and offline capabilities.",
    docsLink: "https://docs.example.com/mobile-app",
    milestones: [
      {
        date: "2024-02-20",
        type: "kickoff",
        name: "Project Start",
        description: "Mobile app project initiated",
        deliverable: "Requirements document",
      },
      {
        date: "2024-03-20",
        type: "design",
        name: "Mobile Design",
        description: "iOS and Android UI design",
        deliverable: "Design mockups",
      },
      {
        date: "2024-04-20",
        type: "development",
        name: "App Development",
        description: "Native app development",
        deliverable: "Beta version",
      },
      {
        date: "2024-05-20",
        type: "launch",
        name: "App Store Launch",
        description: "Release on iOS and Android stores",
        deliverable: "Published apps",
      },
    ],
  },
  {
    id: 3,
    name: "Business Consulting",
    company: "Enterprise Solutions",
    status: "active",
    startedDate: "2023-11-10",
    pipelineState: "finished",
    initialPricing: 8000,
    finalPrice: 9500,
    projectType: "Consulting",
    mmr: 1500,
    paymentStatus: "paid",
    description:
      "Strategic business process optimization and digital transformation consulting for enterprise operations.",
    docsLink: "https://docs.example.com/business-consulting",
    milestones: [
      {
        date: "2023-11-10",
        type: "kickoff",
        name: "Engagement Start",
        description: "Consulting engagement begins",
        deliverable: "Scope document",
      },
      {
        date: "2023-12-10",
        type: "analysis",
        name: "Analysis Phase",
        description: "Business process analysis",
        deliverable: "Analysis report",
      },
      {
        date: "2024-01-10",
        type: "implementation",
        name: "Implementation",
        description: "Process improvements implemented",
        deliverable: "Implementation plan",
      },
      {
        date: "2024-02-10",
        type: "launch",
        name: "Project Completion",
        description: "Consulting project completed",
        deliverable: "Final report",
      },
    ],
  },
  {
    id: 4,
    name: "SaaS Platform",
    company: "CloudVentures",
    status: "active",
    startedDate: "2024-03-05",
    pipelineState: "technical evaluation",
    initialPricing: 50000,
    finalPrice: null,
    projectType: "SaaS",
    mmr: 8000,
    paymentStatus: "pending",
    description: "Cloud-based SaaS platform for team collaboration with advanced reporting and integrations.",
    docsLink: "https://docs.example.com/saas-platform",
    milestones: [
      {
        date: "2024-03-05",
        type: "kickoff",
        name: "Project Initiation",
        description: "SaaS platform project starts",
        deliverable: "Project plan",
      },
      {
        date: "2024-04-05",
        type: "development",
        name: "MVP Development",
        description: "Minimum viable product development",
        deliverable: "MVP release",
      },
      {
        date: "2024-05-05",
        type: "testing",
        name: "Beta Testing",
        description: "Beta testing with early users",
        deliverable: "Beta feedback report",
      },
    ],
  },
  {
    id: 5,
    name: "Data Analytics Tool",
    company: "DataInsights Co",
    status: "active",
    startedDate: "2024-04-01",
    pipelineState: "qualification",
    initialPricing: 12000,
    finalPrice: null,
    projectType: "Software Factory",
    mmr: 2000,
    paymentStatus: "pending",
    description: "Advanced data visualization and analytics tool for business intelligence and predictive analytics.",
    docsLink: "https://docs.example.com/analytics-tool",
    milestones: [
      {
        date: "2024-04-01",
        type: "kickoff",
        name: "Project Kickoff",
        description: "Analytics tool development begins",
        deliverable: "Requirements specification",
      },
      {
        date: "2024-05-01",
        type: "development",
        name: "Feature Development",
        description: "Core analytics features development",
        deliverable: "Initial feature set",
      },
    ],
  },
  {
    id: 6,
    name: "Website Redesign",
    company: "RetailBrand Co",
    status: "active",
    startedDate: "2024-04-15",
    pipelineState: "discovery",
    initialPricing: 5000,
    finalPrice: null,
    projectType: "Consulting",
    mmr: 0,
    paymentStatus: "pending",
    description: "Modern responsive website redesign with improved user experience and conversion optimization.",
    docsLink: "https://docs.example.com/website-redesign",
    milestones: [
      {
        date: "2024-04-15",
        type: "kickoff",
        name: "Discovery Meeting",
        description: "Initial discovery and requirements gathering",
        deliverable: "Discovery document",
      },
      {
        date: "2024-05-15",
        type: "design",
        name: "Website Design",
        description: "New website design creation",
        deliverable: "Design mockups",
      },
    ],
  },
]

// Mock data for contacts
export const contactsData = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@techstartup.com",
    phoneNumber: "+1 (555) 123-4567",
    projectName: "E-commerce Platform",
    position: "CTO",
    company: "TechStartup Inc",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah.j@futureworks.com",
    phoneNumber: "+1 (555) 234-5678",
    projectName: "Mobile App Development",
    position: "Product Manager",
    company: "FutureWorks Ltd",
  },
  {
    id: 3,
    name: "Michael Chen",
    email: "mchen@enterprisesolutions.com",
    phoneNumber: "+1 (555) 345-6789",
    projectName: "Business Consulting",
    position: "COO",
    company: "Enterprise Solutions",
  },
  {
    id: 4,
    name: "Emma Wilson",
    email: "emma.wilson@cloudventures.io",
    phoneNumber: "+1 (555) 456-7890",
    projectName: "SaaS Platform",
    position: "VP Engineering",
    company: "CloudVentures",
  },
  {
    id: 5,
    name: "David Rodriguez",
    email: "david@datainsights.com",
    phoneNumber: "+1 (555) 567-8901",
    projectName: "Data Analytics Tool",
    position: "Founder",
    company: "DataInsights Co",
  },
  {
    id: 6,
    name: "Lisa Anderson",
    email: "lisa.a@retailbrand.com",
    phoneNumber: "+1 (555) 678-9012",
    projectName: "Website Redesign",
    position: "Marketing Director",
    company: "RetailBrand Co",
  },
]
